#!/bin/sh

# configuration:
nick="gitbot"
server="192.168.1.3"
port="6667"
channels="#entropixel"

# don't mess with this unless you have to:
inpipe="/tmp/gitbot/pipe"
tailout="/tmp/gitbot/tail"
ncout="/tmp/gitbot/nc"
pidfile="/tmp/gitbot/pid"

# get netcat command, or telnet
netcat="$(which nc || which netcat || which telnet)"

cleanup () {
	echo "exiting"
	trap '' SIGTERM
	kill 0
	rm -r /tmp/gitbot
	exit 0
}

connattempts=0
parse () {
	printf ">> \033[0;33m%s\033[0m\n" "$1"

	# look for ping
	echo "$1" | egrep -q "^PING" && echo "$1" | sed 's/PING/PONG/' >> "$inpipe" && echo >> "$inpipe"

	# look for end of MOTD
	echo "$1" | egrep -q "^:[^ ]* 376" && for channel in $channels ; do
		echo "JOIN $channel" >> "$inpipe"
	done && connattempts=0
}

conn () {
	# don't let tailout get closed
	tail -f "$inpipe" > "$tailout" &

	# connect
	while true ; do
		if [ $((connattempts += 1)) -lt 5 ] ; then
			# prepare login
			echo "NICK $nick" >> "$inpipe" &
			echo "USER $nick 8 * :$nick" >> "$inpipe" &

			"$netcat" "$server" "$port" < "$tailout" > "$ncout"
		else
			cleanup
		fi
	done &

	# loop, parsing everything we receive from netcat
	while read l ; do
		parse "$l"
	done < "$ncout"

	return 0
}

initialize () {
	# make sure cleanup runs when killed
	trap cleanup SIGTERM
	trap cleanup SIGINT
	trap cleanup SIGHUP

	# set up run directory
	[ -d /tmp/gitbot ] && echo "run directory exists" && exit 1
	mkdir -p /tmp/gitbot

	# write channels (for the git hook)
	echo "$channels" > /tmp/gitbot/channels

	# make input pipes
	mkfifo "$inpipe"
	mkfifo "$tailout"
	mkfifo "$ncout"

	echo "$$" > "$pidfile"

	# connect to IRC
	conn
}

# daemonize
if [ "$1" = "-d" ] ; then
	("$0" &) > /dev/null 2>&1
	exit 0
fi

initialize
